DURATIONS = 5
DURATIONS_RECOG = 10
DIRECTORY_SAMPELS = 'tmp'
COUNT_EXAMPLES_VOICE = 5
TEMPLATE_NAME_EXAMPLES_VOICE = "example_{}.wav"
TEMPLATE_REC_VOICE = "record.wav"

TEMPLATE_NAME_RECORD = "tmp_record.wav"