DURATIONS = 5
DURATIONS_RECOG = 10
DIRECTORY_SAMPELS = 'api/tmp'
PATH_MODEL = 'api/model/biometry_model.ckpt'
COUNT_EXAMPLES_VOICE = 5
TEMPLATE_NAME_EXAMPLES_VOICE = "example_{}.wav"
TEMPLATE_REC_VOICE = "record.wav"
